# K - MEANS CLUSTERING

# IMPORTING LIBRARIES

In [1]:
import cv2
import numpy as np

In [2]:
img=cv2.imread("C:/Users/SN131/Desktop/football.jpg")


# RGB CONVERSION

In [4]:
imgrgb = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

# RESHAPE

In [5]:
vec = imgrgb.reshape((-1,3))
vec

array([[ 2,  5, 14],
       [ 2,  5, 14],
       [ 2,  5, 14],
       ...,
       [ 0,  4, 13],
       [ 0,  4, 13],
       [ 1,  5, 14]], dtype=uint8)

# FLOAT CONVERSION

In [6]:
vec = np.float32(vec)
vec

array([[ 2.,  5., 14.],
       [ 2.,  5., 14.],
       [ 2.,  5., 14.],
       ...,
       [ 0.,  4., 13.],
       [ 0.,  4., 13.],
       [ 1.,  5., 14.]], dtype=float32)

# ITERATION TERMINATION CRITERIA

In [9]:
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER,100,1)

# CLUSTER CONDITION

In [10]:
k = 3
attempts = 100

# K - MEANS CLUSTERING

In [11]:
compactness,label,center = cv2.kmeans(vec,k,None,criteria,attempts,cv2.KMEANS_PP_CENTERS)
center

array([[217.6746  , 209.18068 , 181.16965 ],
       [ 12.642567,  31.81795 ,  51.388622],
       [128.47084 , 104.74736 , 110.16346 ]], dtype=float32)

In [13]:
center = np.uint8(center)
center

array([[217, 209, 181],
       [ 12,  31,  51],
       [128, 104, 110]], dtype=uint8)

## FLATTENING AND RESHAPE

In [14]:
res = center[label.flatten()]
res_img = res.reshape((imgrgb.shape))
res_img

array([[[12, 31, 51],
        [12, 31, 51],
        [12, 31, 51],
        ...,
        [12, 31, 51],
        [12, 31, 51],
        [12, 31, 51]],

       [[12, 31, 51],
        [12, 31, 51],
        [12, 31, 51],
        ...,
        [12, 31, 51],
        [12, 31, 51],
        [12, 31, 51]],

       [[12, 31, 51],
        [12, 31, 51],
        [12, 31, 51],
        ...,
        [12, 31, 51],
        [12, 31, 51],
        [12, 31, 51]],

       ...,

       [[12, 31, 51],
        [12, 31, 51],
        [12, 31, 51],
        ...,
        [12, 31, 51],
        [12, 31, 51],
        [12, 31, 51]],

       [[12, 31, 51],
        [12, 31, 51],
        [12, 31, 51],
        ...,
        [12, 31, 51],
        [12, 31, 51],
        [12, 31, 51]],

       [[12, 31, 51],
        [12, 31, 51],
        [12, 31, 51],
        ...,
        [12, 31, 51],
        [12, 31, 51],
        [12, 31, 51]]], dtype=uint8)

# IMAGE PROCESSING

In [16]:
cv2.imshow("img",img)
cv2.imshow("segmented",res_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
img=cv2.imread("C:/Users/SN131/Desktop/football.jpg")
segmented_image = cv2.pyrMeanShiftFiltering(img,40,40)
cv2.imshow("img",img)
cv2.imshow("segmented_image",segmented_image)
cv2.waitKey(0)
cv2.destroyAllWindows()